In [1]:
'''
Implementation of simple digit recognizer using CNN
@Author: Rohith Uppala
'''

'\nImplementation of simple digit recognizer using CNN\n@Author: Rohith Uppala\n'

In [5]:
import torch
from torch import nn
import numpy as np
import pandas

In [6]:
arr = torch.Tensor([1,2,3])
arr

tensor([1., 2., 3.])

In [7]:
import os
os.listdir('input')

['test.csv', 'train.csv']

In [8]:
tensor = torch.ones(3,3)

In [9]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
tensor.mean()

tensor(1.)

In [11]:
tensor.std()

tensor(0.)

In [13]:
from torch.autograd import Variable
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad=True)
y = x**2
o = 1/2 * sum(y)
o

tensor(10., grad_fn=<MulBackward0>)

In [14]:
o.backward()

In [15]:
o

tensor(10., grad_fn=<MulBackward0>)

In [16]:
x.grad

tensor([2., 4.])

In [23]:
var = [1,2,3]
var_np = np.array(var)
var_np.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [24]:
car_prices_tensor

NameError: name 'car_prices_tensor' is not defined

In [26]:
car_prices_array = [3,4,5,6,7,8]
car_prices_np = np.array(car_prices_array, dtype=np.float32)
car_prices_np = car_prices_np.reshape(-1, 1)
car_prices_tensor = Variable(torch.from_numpy(car_prices_np))

In [27]:
car_prices_tensor

tensor([[3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])

In [34]:
import torch
from torch.autograd import Variable
import torch.nn as nn


class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        return self.linear(x)

In [35]:
input_dim, output_dim = 1, 1
model = LinearRegression(input_dim, output_dim)

In [37]:
mse = nn.MSELoss()

In [39]:
car_prices_array = [3,4,5,6,7,8,9]
car_price_np = np.array(car_prices_array,dtype=np.float32)
car_price_np = car_price_np.reshape(-1,1)
car_price_tensor = Variable(torch.from_numpy(car_price_np))

# lets define number of car sell
number_of_car_sell_array = [ 7.5, 7, 6.5, 6.0, 5.5, 5.0, 4.5]
number_of_car_sell_np = np.array(number_of_car_sell_array,dtype=np.float32)
number_of_car_sell_np = number_of_car_sell_np.reshape(-1,1)
number_of_car_sell_tensor = Variable(torch.from_numpy(number_of_car_sell_np))


mse

In [38]:
learning_rate = 0.02
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [43]:
loss_list = []
iterations = 1001

for iteration in range(iterations):
    optimizer.zero_grad()
    result = model(car_price_tensor)
    loss = mse(result, number_of_car_sell_tensor)
    loss.backward()
    optimizer.step()
    loss_list.append(loss.data)
    if iteration % 50 == 0:
        print('epoch: {}, loss: {}'.format(iteration, loss.data))

epoch: 0, loss: 0.0025788689963519573
epoch: 50, loss: 0.001742619788274169
epoch: 100, loss: 0.0011774415615946054
epoch: 150, loss: 0.0007956200861372054
epoch: 200, loss: 0.0005376405315473676
epoch: 250, loss: 0.0003633511660154909
epoch: 300, loss: 0.0002455257053952664
epoch: 350, loss: 0.0001659225526964292
epoch: 400, loss: 0.00011212196841370314
epoch: 450, loss: 7.576159987365827e-05
epoch: 500, loss: 5.11907201143913e-05
epoch: 550, loss: 3.4596858313307166e-05
epoch: 600, loss: 2.3381087885354646e-05
epoch: 650, loss: 1.5799148968653753e-05
epoch: 700, loss: 1.0675554221961647e-05
epoch: 750, loss: 7.214571269287262e-06
epoch: 800, loss: 4.876555067312438e-06
epoch: 850, loss: 3.295488113508327e-06
epoch: 900, loss: 2.227135382781853e-06
epoch: 950, loss: 1.5059629276947817e-06
epoch: 1000, loss: 1.018510147332563e-06


In [44]:
car_price_tensor

tensor([[3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [45]:
predicted = model(car_price_tensor).data.numpy()

In [46]:
predicted

array([[7.4982553],
       [6.9987335],
       [6.4992113],
       [5.999689 ],
       [5.5001674],
       [5.0006456],
       [4.5011234]], dtype=float32)

In [ ]:
# Import Libraries
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from torch.autograd import Variable
import pandas as pd
import numpy as np
import pandas as pd
import pdb
from sklearn.model_selection import train_test_split

In [ ]:
# Prepare Dataset
# load data
train = pd.read_csv(r"input/train.csv",dtype = np.float32)

# split data into features(pixels) and labels(numbers from 0 to 9)
targets_numpy = train.label.values
features_numpy = train.loc[:,train.columns != "label"].values/255 # normalization

# train test split. Size of train data is 80% and size of test data is 20%. 
features_train, features_test, targets_train, targets_test = train_test_split(features_numpy,
                                                                             targets_numpy,
                                                                             test_size = 0.2,
                                                                             random_state = 42) 

# create feature and targets tensor for train set. As you remember we need variable to accumulate gradients. Therefore first we create tensor, then we will create variable
featuresTrain = torch.from_numpy(features_train)
targetsTrain = torch.from_numpy(targets_train).type(torch.LongTensor) # data type is long

# create feature and targets tensor for test set.
featuresTest = torch.from_numpy(features_test)
targetsTest = torch.from_numpy(targets_test).type(torch.LongTensor) # data type is long

# batch_size, epoch and iteration
batch_size = 100
n_iters = 10000
num_epochs = n_iters / (len(features_train) / batch_size)
num_epochs = int(num_epochs)


# Pytorch train and test sets
train = torch.utils.data.TensorDataset(featuresTrain,targetsTrain)
test = torch.utils.data.TensorDataset(featuresTest,targetsTest)

# data loader
train_loader = torch.utils.data.DataLoader(train, batch_size = batch_size, shuffle = False)
test_loader = torch.utils.data.DataLoader(test, batch_size = batch_size, shuffle = False)

In [ ]:
# Create Logistic Regression Model
class LogisticRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegressionModel, self).__init__()
        # Linear part
        self.linear = nn.Linear(input_dim, output_dim)
        # There should be logistic function right?
        # However logistic function in pytorch is in loss function
        # So actually we do not forget to put it, it is only at next parts
    
    def forward(self, x):
        out = self.linear(x)
        return out

# Instantiate Model Class
input_dim = 28*28 # size of image px*px
output_dim = 10  # labels 0,1,2,3,4,5,6,7,8,9

# create logistic regression model
model = LogisticRegressionModel(input_dim, output_dim)

# Cross Entropy Loss  
error = nn.CrossEntropyLoss()

# SGD Optimizer 
learning_rate = 0.001
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [ ]:
count = 0
for epoch in range(num_epochs):
    print("Running epoch: {}".format(epoch))
    for i, (images, labels) in enumerate(train_loader):
        batch_train = Variable(images.view(-1, 28*28))
        labels = Variable(labels)
        optimizer.zero_grad()
        outputs = model(batch_train)
        loss = error(outputs, labels)
        loss.backward()
        optimizer.step()
        count = count + 1
        if count % 500 == 0:
            correct, total = 0, 0
            for images, labels in test_loader:
                batch_test = Variable(images.view(-1, 28*28))
                ouputs = model(batch_test)
                predicted = torch.max(outputs.data, 1)[1]
                total += len(labels)
                correct += (predicted == labels).sum()
            accuracy = 100 * correct / float(total)
            print('Iteration: {}, Loss: {}, Accuracy: {}%'.format(count, loss.data, accuracy))